create or alter procedure LECTURE_ACTIVE_IU (
    ID type of column LECTURE_ACTIVE.ID,
    DONG_ID type of column LECTURE_ACTIVE.DONG_ID,
    L_YEAR type of column LECTURE_ACTIVE.L_YEAR,
    L_STEP type of column LECTURE_ACTIVE.L_STEP,
    L_NAME type of column LECTURE_ACTIVE.L_NAME,
    L_TIME_WEEK type of column LECTURE_ACTIVE.L_TIME_WEEK,
    L_DAYS type of column LECTURE_ACTIVE.L_DAYS,
    L_MONTH type of column LECTURE_ACTIVE.L_MONTH,
    START_DATE type of column LECTURE_ACTIVE.START_DATE,
    TEACHER_ID type of column LECTURE_ACTIVE.TEACHER_ID,
    L_PRICE type of column LECTURE_ACTIVE.L_PRICE,
    CLASSROOM_ID type of column LECTURE_ACTIVE.CLASSROOM_ID,
    IS_ACTIVE type of column LECTURE_ACTIVE.IS_ACTIVE,
    L_DURATION type of column LECTURE_ACTIVE.L_DURATION,
    L_TIME type of column LECTURE_ACTIVE.L_TIME,
    L_TIME_START type of column LECTURE_ACTIVE.L_TIME_START,
    L_TIME_END type of column LECTURE_ACTIVE.L_TIME_END,
    END_DATE type of column LECTURE_ACTIVE.END_DATE,
    PLAN_MEN type of column LECTURE_ACTIVE.PLAN_MEN,
    REGIST_MEN type of column LECTURE_ACTIVE.REGIST_MEN,
    WAIT_MEN type of column LECTURE_ACTIVE.WAIT_MEN,
    DROP_MEN type of column LECTURE_ACTIVE.DROP_MEN,
    TOTAL_DAY type of column LECTURE_ACTIVE.TOTAL_DAY,
    TOTAL_TIME type of column LECTURE_ACTIVE.TOTAL_TIME,
    TEACHER_PERCENT type of column LECTURE_ACTIVE.TEACHER_PERCENT)
as
begin
  if (exists(select id from lecture_active where (id = :id))) then
    update lecture_active
    set dong_id = :dong_id,
        l_year = :l_year,
        l_step = :l_step,
        l_name = :l_name,
        l_time_week = :l_time_week,
        l_days = :l_days,
        l_month = :l_month,
        start_date = :start_date,
        teacher_id = :teacher_id,
        l_price = :l_price,
        classroom_id = :classroom_id,
        is_active = :is_active,
        l_duration = :l_duration,
        l_time = :l_time,
        l_time_start = :l_time_start,
        l_time_end = :l_time_end,
        end_date = :end_date,
        plan_men = :plan_men,
        regist_men = :regist_men,
        wait_men = :wait_men,
        drop_men = :drop_men,
        total_day = :total_day,
        total_time = :total_time,
        teacher_percent = :teacher_percent
    where (id = :id);
  else
    insert into lecture_active (
        id,
        dong_id,
        l_year,
        l_step,
        l_name,
        l_time_week,
        l_days,
        l_month,
        start_date,
        teacher_id,
        l_price,
        classroom_id,
        is_active,
        l_duration,
        l_time,
        l_time_start,
        l_time_end,
        end_date,
        plan_men,
        regist_men,
        wait_men,
        drop_men,
        total_day,
        total_time,
        teacher_percent)
    values (
        :id,
        :dong_id,
        :l_year,
        :l_step,
        :l_name,
        :l_time_week,
        :l_days,
        :l_month,
        :start_date,
        :teacher_id,
        :l_price,
        :classroom_id,
        :is_active,
        :l_duration,
        :l_time,
        :l_time_start,
        :l_time_end,
        :end_date,
        :plan_men,
        :regist_men,
        :wait_men,
        :drop_men,
        :total_day,
        :total_time,
        :teacher_percent);
end