SET TERM #;
CREATE GENERATOR GEN_MONEY_OUT_REPORT2_ID;
#
CREATE TABLE MONEY_OUT_REPORT2 (
    ID           INTEGER NOT NULL,
    M_YEAR       INTEGER,
    BALUI_DATE   DATE,
    OUT_DATE     DATE,
    REG_DATE1    DATE,
    REG_DATE2    DATE,
    OUT_AMOUNT   DOUBLE PRECISION,
    BANK_NAME    VARCHAR(20),
    BANK_ID      VARCHAR(30),
    BANK_OWENER  VARCHAR(20),
    OWENER_ADDR  VARCHAR(50),
    AWENER_COMP  VARCHAR(30),
    BIGO         VARCHAR(100),
    DONG_ID      VARCHAR(17),
    UNIQ_ID      VARCHAR(17),
    M_DATE       DATE,
    OUT_LIST 		 VARCHAR(500)
);
#
ALTER TABLE MONEY_OUT_REPORT2 ADD CONSTRAINT PK_MONEY_OUT_REPORT2 PRIMARY KEY (ID);
#
CREATE OR ALTER TRIGGER MONEY_OUT_REPORT2_BI FOR MONEY_OUT_REPORT2
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_money_out_report2_id,1);
end
#
SET TERM ;#
