SET TERM #;
CREATE GENERATOR GEN_MONEY_BACK_REPORT2_ID;
#
CREATE TABLE MONEY_BACK_REPORT2 (
    ID             INTEGER NOT NULL,
    M_YEAR         INTEGER,
    BALUI_DATE     DATE,
    OUT_DATE       DATE,
    REG_DATE1      DATE,
    REG_DATE2      DATE,
    OUT_AMOUNT     DOUBLE PRECISION,
    LECTURE_NAME   VARCHAR(30),
    LECTURE_SNAME  VARCHAR(20),
    PAY_DATE       DATE,
    PAY_AMOUNT     DOUBLE PRECISION,
    BACK_REASON    VARCHAR(20),
    REQ_ADDR       VARCHAR(100),
    REQ_TEL        VARCHAR(20),
    REQ_NAME       VARCHAR(20),
    REQ_BANK       VARCHAR(30),
    REQ_BANKID     VARCHAR(30),
    DONG_ID        VARCHAR(17),
    UNIQ_ID        VARCHAR(17),
    M_DATE         DATE
);
#
ALTER TABLE MONEY_BACK_REPORT2 ADD CONSTRAINT PK_MONEY_BACK_REPORT2 PRIMARY KEY (ID);
#
CREATE OR ALTER TRIGGER MONEY_BACK_REPORT2_BI FOR MONEY_BACK_REPORT2
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_money_back_report2_id,1);
end
#
SET TERM ; #
