SET TERM # ;
CREATE GENERATOR GEN_TEACHER_COMPANSATION_ID;
#
CREATE TABLE TEACHER_COMPANSATION (
    ID                  INTEGER NOT NULL,
    LECTURE_ID          VARCHAR(17),
    PAY_MONTH           INTEGER,
    REG_TOTAL_CNT       INTEGER DEFAULT 0,
    DC_TOTAL_CNT        INTEGER DEFAULT 0,
    DC_KIND1_CNT        INTEGER DEFAULT 0,
    DC_KIND2_CNT        INTEGER DEFAULT 0,
    DC_KIND3_CNT        INTEGER DEFAULT 0,
    DC_KIND4_CNT        INTEGER DEFAULT 0,
    DC_KIND5_CNT        INTEGER DEFAULT 0,
    DC_KIND6_CNT        INTEGER DEFAULT 0,
    COMPANSATION_PRICE  FLOAT DEFAULT 0,
    TOTAL_PRICE         FLOAT DEFAULT 0
);
#
ALTER TABLE TEACHER_COMPANSATION ADD CONSTRAINT PK_TEACHER_COMPANSATION PRIMARY KEY (ID);
#
CREATE OR ALTER TRIGGER TEACHER_COMPANSATION_BI FOR TEACHER_COMPANSATION
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.id is null) then
    new.id = gen_id(gen_teacher_compansation_id,1);
end
#
SET TERM ; #