INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (1, '08:00');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (7, '08:30');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (13, '09:00');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (19, '09:30');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (25, '10:00');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (31, '10:30');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (37, '11:00');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (43, '11:30');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (49, '12:00');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (55, '12:30');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (61, '13:00');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (67, '13:30');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (73, '14:00');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (79, '14:30');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (85, '15:00');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (91, '15:30');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (97, '16:00');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (103, '16:30');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (109, '17:00');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (115, '17:30');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (121, '18:00');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (127, '18:30');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (133, '19:00');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (139, '19:30');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (145, '20:00');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (151, '20:30');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (157, '21:00');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (163, '21:30');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (169, '22:00');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (174, '22:25');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (2, '08:05');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (3, '08:10');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (4, '08:15');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (5, '08:20');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (6, '08:25');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (8, '08:35');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (9, '08:40');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (10, '08:45');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (11, '08:50');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (12, '08:55');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (14, '09:05');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (15, '09:10');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (16, '09:15');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (17, '09:20');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (18, '09:25');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (20, '09:35');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (21, '09:40');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (22, '09:45');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (23, '09:50');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (24, '09:55');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (26, '10:05');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (27, '10:10');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (28, '10:15');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (29, '10:20');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (30, '10:25');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (32, '10:35');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (33, '10:40');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (34, '10:45');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (35, '10:50');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (36, '10:55');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (38, '11:05');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (39, '11:10');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (40, '11:15');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (41, '11:20');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (42, '11:25');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (44, '11:35');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (45, '11:40');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (46, '11:45');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (47, '11:50');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (48, '11:55');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (50, '12:05');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (51, '12:10');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (52, '12:15');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (53, '12:20');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (54, '12:25');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (56, '12:35');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (57, '12:40');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (58, '12:45');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (59, '12:50');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (60, '12:55');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (62, '13:05');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (63, '13:10');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (64, '13:15');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (65, '13:20');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (66, '13:25');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (68, '13:35');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (69, '13:40');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (70, '13:45');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (71, '13:50');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (72, '13:55');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (74, '14:05');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (75, '14:10');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (76, '14:15');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (77, '14:20');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (78, '14:25');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (80, '14:35');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (81, '14:40');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (82, '14:45');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (83, '14:50');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (84, '14:55');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (86, '15:05');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (87, '15:10');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (88, '15:15');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (89, '15:20');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (90, '15:25');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (92, '15:35');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (93, '15:40');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (94, '15:45');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (95, '15:50');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (96, '15:55');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (98, '16:05');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (99, '16:10');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (100, '16:15');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (101, '16:20');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (102, '16:25');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (104, '16:35');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (105, '16:40');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (106, '16:45');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (107, '16:50');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (108, '16:55');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (110, '17:05');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (111, '17:10');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (112, '17:15');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (113, '17:20');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (114, '17:25');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (116, '17:35');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (117, '17:40');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (118, '17:45');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (119, '17:50');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (120, '17:55');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (122, '18:05');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (123, '18:10');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (124, '18:15');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (125, '18:20');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (126, '18:25');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (128, '18:35');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (129, '18:40');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (130, '18:45');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (131, '18:50');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (132, '18:55');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (134, '19:05');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (135, '19:10');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (136, '19:15');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (137, '19:20');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (138, '19:25');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (140, '19:35');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (141, '19:40');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (142, '19:45');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (143, '19:50');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (144, '19:55');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (146, '20:05');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (147, '20:10');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (148, '20:15');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (149, '20:20');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (150, '20:25');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (152, '20:35');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (153, '20:40');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (154, '20:45');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (155, '20:50');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (156, '20:55');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (158, '21:05');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (159, '21:10');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (160, '21:15');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (161, '21:20');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (162, '21:25');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (164, '21:35');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (165, '21:40');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (166, '21:45');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (167, '21:50');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (168, '21:55');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (170, '22:05');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (171, '22:10');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (172, '22:15');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (173, '22:20');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (175, '22:30');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (176, '22:35');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (177, '22:40');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (178, '22:45');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (179, '22:50');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (180, '22:55');
INSERT INTO TIME_TABLE (ID, TIME_STR)
                VALUES (181, '23:00');

COMMIT WORK;
